```{r}
# Load libraries
library(scater)
library(Seurat)
library(tidyverse)
library(cowplot)
library(Matrix.utils)
library(edgeR)
library(dplyr)
library(magrittr)
library(Matrix)
library(purrr)
library(reshape2)
library(S4Vectors)
library(tibble)
library(SingleCellExperiment)
library(pheatmap)
library(apeglm)
library(png)
library(DESeq2)
library(RColorBrewer)
library(ArchR)
library(MetBrewer)
```

```{r}
lvad <- readRDS("../4 - postContamination/harmony_annotated.rds")
```

```{r}
lvad$bulk <- "bulk"
```

```{r}
seurat <- lvad
seurat$orig.ident <- gsub("-", "", seurat$orig.ident)
seurat$orig.ident <- gsub("_", "", seurat$orig.ident)

# Extract raw counts and metadata to create SingleCellExperiment object
counts <- seurat@assays$RNA@counts 

metadata <- seurat@meta.data

# Set up metadata as desired for aggregation and DE analysis
metadata$cluster_id <- factor(seurat$cell.type)
#metadata$cluster_id <- factor(seurat$bulk) # all samples PCA
metadata$sample_id <- factor(seurat$orig.ident)
metadata$group_id <- factor(seurat$condition)

# Create single cell experiment object
sce <- SingleCellExperiment(assays = list(counts = counts), 
                           colData = metadata)

# Identify groups for aggregation of counts
groups <- colData(sce)[, c("cluster_id", "sample_id")]

# Named vector of cluster names
kids <- purrr::set_names(levels(sce$cluster_id))

# Total number of clusters
nk <- length(kids)

# Named vector of sample names
sids <- purrr::set_names(levels(sce$sample_id))

# Total number of samples 
ns <- length(sids)

# Generate sample level metadata

## Turn named vector into a numeric vector of number of cells per sample
n_cells <- as.numeric(table(sce$sample_id))

## Determine how to reoder the samples (rows) of the metadata to match the order of sample names in sids vector
m <- match(sids, sce$sample_id)

## Create the sample level metadata by combining the reordered metadata with the number of cells corresponding to each sample.
ei <- data.frame(colData(sce)[m, ], 
                  n_cells, row.names = NULL) %>% 
                select(-"cluster_id")

## Remove lowly expressed genes which have less than 10 cells with any counts
sce <- sce[rowSums(counts(sce) > 1) >= 10, ]
# Aggregate the counts per sample_id and cluster_id

# Subset metadata to only include the cluster and sample IDs to aggregate across
groups <- colData(sce)[, c("cluster_id", "sample_id")]

# Aggregate across cluster-sample groups
pb <- aggregate.Matrix(t(counts(sce)), 
                       groupings = groups, fun = "sum") 

# Not every cluster is present in all samples; create a vector that represents how to split samples
splitf <- sapply(stringr::str_split(rownames(pb), 
                                    pattern = "_",  
                                    n = 2), 
                 `[`, 1)

# Turn into a list and split the list into components for each cluster and transform, so rows are genes and columns are samples and make rownames as the sample IDs
pb <- split.data.frame(pb, 
                       factor(splitf)) %>%
        lapply(function(u) 
                set_colnames(t(u), 
                             stringr::str_extract(rownames(u), "(?<=_)[:alnum:]+")))

# Get sample names for each of the cell type clusters

# prep. data.frame for plotting
get_sample_ids <- function(x){
        pb[[x]] %>%
                colnames()
}

de_samples <- map(1:length(kids), get_sample_ids) %>%
        unlist()

# Get cluster IDs for each of the samples

samples_list <- map(1:length(kids), get_sample_ids)

get_cluster_ids <- function(x){
        rep(names(pb)[x], 
            each = length(samples_list[[x]]))
}

de_cluster_ids <- map(1:length(kids), get_cluster_ids) %>%
        unlist()

# Create a data frame with the sample IDs, cluster IDs and condition

gg_df <- data.frame(cluster_id = de_cluster_ids,
                    sample_id = de_samples)

gg_df <- left_join(gg_df, ei[, c("sample_id", "group_id")]) 


metadata <- gg_df %>%
        dplyr::select(cluster_id, sample_id, group_id) 
        
```

```{r}
unique(metadata$sample_id)
```

```{r}
# Generate vector of cluster IDs
clusters <- unique(metadata$cluster_id)
clusters
```

# Create PCA Plots
```{r}
cluster_number <- 1

# Subset the metadata to only the B cells
cluster_metadata <- metadata[which(metadata$cluster_id == clusters[cluster_number]), ]
#head(cluster_metadata)

# Assign the rownames of the metadata to be the sample IDs
rownames(cluster_metadata) <- cluster_metadata$sample_id
#head(cluster_metadata)

# Subset the counts to only cluster of interest
counts <- pb[[clusters[cluster_number]]]

cluster_counts <- data.frame(counts[, which(colnames(counts) %in% rownames(cluster_metadata))])

# Check that all of the row names of the metadata are the same and in the same order as the column names of the counts in order to use as input to DESeq2
#all(rownames(cluster_metadata) == colnames(cluster_counts))        

dds <- DESeqDataSetFromMatrix(cluster_counts, 
                              colData = cluster_metadata, 
                              design = ~ group_id)

# Transform counts for data visualization
rld <- rlog(dds, blind=TRUE)
```

```{r}
rld$group_id <- factor(rld$group_id, levels =c("Donor","NRpre","Rpre","NRpost","Rpost"))
pcaData <- plotPCA(rld, intgroup=c("group_id"), returnData=TRUE, ntop = 500)
percentVar <- round(100 * attr(pcaData, "percentVar"))
ggplot(pcaData, aes(PC1, PC2, color=group_id)) + xlim(-27,20) + ylim(-20,20) +
  geom_point(size=3) + geom_density_2d(bins = 7, contour_var="count") +
  scale_color_manual(values=as.vector(paletteDiscrete(unique(rld$group_id), set = "stallion"))) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))
```

```{r}
pcaData <- plotPCA(rld, intgroup=c("group_id"), returnData=TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))
ggplot(pcaData, aes(PC1, PC2, color=group_id)) +
  geom_point(size=2) +
  coord_fixed() + theme_bw() +
  stat_ellipse(geom = "polygon", alpha = 0.1, aes(fill = group_id)) +
  scale_color_manual(values=as.vector(paletteDiscrete(unique(rld$group_id), set = "stallion"))) + 
  scale_fill_manual(values=as.vector(paletteDiscrete(unique(rld$group_id), set = "stallion"))) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) 
```

```{r}
rld$group_id <- factor(rld$group_id, levels =c("Donor","NRpre","Rpre","NRpost","Rpost"))
pcaData <- plotPCA(rld, intgroup=c("group_id"), returnData=TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))
ggplot(pcaData, aes(PC1, PC2, color=group_id)) +
  geom_point(size=1.5) +
  theme_bw() + geom_text_repel(aes(label = pcaData$name),
                    size = 2) +
  scale_color_manual(values=as.vector(paletteDiscrete(unique(rld$group_id), set = "stallion"))) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) 
```

# Functionalize DDS
```{r}
get_dds_results <- function(cluster_number, metadata_subset, fname){

# Subset the metadata to only the B cells
cluster_metadata <- metadata_subset[which(metadata_subset$cluster_id == clusters[cluster_number]), ]
#head(cluster_metadata)

# Assign the rownames of the metadata to be the sample IDs
rownames(cluster_metadata) <- cluster_metadata$sample_id
#head(cluster_metadata)

# Subset the counts to only cluster of interest
counts_matrix <- pb[[clusters[cluster_number]]]

cluster_counts <- data.frame(counts_matrix[, which(colnames(counts_matrix) %in% rownames(cluster_metadata))])

# Check that all of the row names of the metadata are the same and in the same order as the column names of the counts in order to use as input to DESeq2
#all(rownames(cluster_metadata) == colnames(cluster_counts))        

dds <- DESeqDataSetFromMatrix(cluster_counts, 
                              colData = cluster_metadata, 
                              design = ~ HF)

# Transform counts for data visualization
rld <- rlog(dds, blind=TRUE)

# Extract the rlog matrix from the object and compute pairwise correlation values
rld_mat <- assay(rld)
rld_cor <- cor(rld_mat)

# Run DESeq2 differential expression analysis
dds <- DESeq(dds)

# Plot dispersion estimates
# Plot dispersion estimates
png(paste0("DE_analysis/", fname, "/", clusters[cluster_number], "_dispersion_plot.png"))
plotDispEsts(dds)
dev.off()

# Output results of Wald test for contrast for stim vs ctrl
unique(cluster_metadata$HF)[2]
unique(cluster_metadata$HF)[1]

contrast <- c("HF", unique(cluster_metadata$HF)[2], unique(cluster_metadata$HF)[1])

# resultsNames(dds)
res <- results(dds, 
               contrast = contrast,
               alpha = 0.05)

res <- lfcShrink(dds, 
                 contrast =  contrast,
                 res=res,
                 type="ashr")

# Turn the results object into a tibble for use with tidyverse functions
res_tbl <- res %>%
        data.frame() %>%
        rownames_to_column(var="gene") %>%
        as_tibble()

write.csv(res_tbl,
          paste0("DE_analysis/", fname, "/", clusters[cluster_number], "_", unique(cluster_metadata$HF)[2], "_vs_", unique(cluster_metadata$HF)[1], "_all_genes.csv"),
          quote = FALSE, 
          row.names = FALSE)

# Set thresholds
padj_cutoff <- 0.05

# Subset the significant results
sig_res <- dplyr::filter(res_tbl, padj < padj_cutoff) %>%
        dplyr::arrange(padj)

# Write significant results to file
write.csv(sig_res,
          paste0("DE_analysis/", fname, "/", clusters[cluster_number], "_", unique(cluster_metadata$HF)[2], "_vs_", unique(cluster_metadata$HF)[1], "_sig_genes.csv"),
          quote = FALSE, 
          row.names = FALSE)
        
}
```

# Donor vs HF
```{r}
metadata$HF <- ifelse(metadata$group_id == "Donor", "Donor", "HF")
```

```{r}
# Run the script on all clusters comparing stim condition relative to control condition
map(1:length(clusters), get_dds_results, metadata_subset = metadata, fname = "HF_Donor")
```

# R/NR Pre vs R-Post
```{r}
metadata_subset <- subset(metadata, metadata$group_id %in% c("Rpre","NRpre","Rpost"))
metadata_subset$HF <- ifelse(metadata_subset$group_id == "Rpost", "Rpost", "RNRPre")
```

```{r}
# Run the script on all clusters comparing stim condition relative to control condition
map(1:length(clusters), get_dds_results, metadata_subset = metadata_subset, fname = "Rpost_RNRPre")
```

# NR post vs R post
```{r}
metadata_subset <- subset(metadata, metadata$group_id %in% c("NRpost","Rpost"))
metadata_subset$HF <- ifelse(metadata_subset$group_id == "NRpost", "NRpost", "Rpost")
```

```{r}
# Run the script on all clusters comparing stim condition relative to control condition
map(1:length(clusters), get_dds_results, metadata_subset = metadata_subset, fname = "NRpost_Rpost")
```

# NR pre vs R pre
```{r}
metadata_subset <- subset(metadata, metadata$group_id %in% c("NRpre","Rpre"))
metadata_subset$HF <- ifelse(metadata_subset$group_id == "NRpre", "NRpre", "Rpre")
```

```{r}
# Run the script on all clusters comparing stim condition relative to control condition
map(1:length(clusters), get_dds_results, metadata_subset = metadata_subset, fname = "NRpre_Rpre")
```

# Rpre vs Rpost
```{r}
metadata_subset <- subset(metadata, metadata$group_id %in% c("Rpre","Rpost"))
metadata_subset$HF <- ifelse(metadata_subset$group_id == "Rpost", "Rpost", "Rpre")
```

```{r}
# Run the script on all clusters comparing stim condition relative to control condition
map(1:length(clusters), get_dds_results, metadata_subset = metadata_subset, fname = "Rpre_Rpost")
```

# R/NR Pre vs Donor
```{r}
metadata_subset <- subset(metadata, metadata$group_id %in% c("Rpre","NRpre","Donor"))
metadata_subset$HF <- ifelse(metadata_subset$group_id == "Donor", "Donor", "R_NR_Pre")
```

```{r}
# Run the script on all clusters comparing stim condition relative to control condition
map(1:length(clusters), get_dds_results, metadata_subset = metadata_subset, fname = "RNRpre_Donor")
```

# RPost vs Donor
```{r}
metadata_subset <- subset(metadata, metadata$group_id %in% c("Rpost","Donor"))
metadata_subset$HF <- ifelse(metadata_subset$group_id == "Donor", "Donor", "Rpost")
```

```{r}
# Run the script on all clusters comparing stim condition relative to control condition
map(1:length(clusters), get_dds_results, metadata_subset = metadata_subset, fname = "Rpost_Donor")
```

# Rpost vs Donor+HF
```{r}
metadata_subset <- subset(metadata, metadata$group_id %in% c("Rpre","NRpre","Donor","Rpost"))
metadata_subset$HF <- ifelse(metadata_subset$group_id == "Rpost", "Rpost", "DonorHF")
```

```{r}
# Run the script on all clusters comparing stim condition relative to control condition
map(1:length(clusters), get_dds_results, metadata_subset = metadata_subset, fname = "DonorHF_Rpost")
```






















